name: Update Readme Table from CSV

on:
  push:
    paths:
      - 'data.csv' # قم بتغيير data.csv لاسم ملفك إذا كان مختلفاً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto-generate table in README
        uses: tsub/action-csv-to-markdown-table@v1
        with:
          csv_path: 'data.csv' # مسار ملف الـ CSV الخاص بك
          readme_path: 'README.md'

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.io'
          git add README.md
          git diff-index --quiet HEAD || git commit -m "تحديث تلقائي لجدول README من CSV"
          git push
